### ISSUE TITLE
log/friendica.log  is missing

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/friendica_ynh#66]
### Describe the bug

<path_to_install_root>/log/friendica.log  is missing after a fresh install

### Context

- Hardware: *VPS bought online*
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 4.3.4.2
yunohost-admin: 
  repo: stable
  version: 4.3.2.3
moulinette: 
  repo: stable
  version: 4.3.2.2
ssowat: 
  repo: stable
  version: 4.3.2.2
  ```
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:
```
name: Friendica
version: 2021.09~ynh1
```
### Steps to reproduce

no `log` folder in `/var/www/friendica/`
### Expected behavior

`/var/www/friendica/log/friendica.log`  should exists, with ownership `friendica:www-data`  
* it could be a ln -s to `/var/log/friendica.log`  
* it should be managed via logrotate
